module_7
dmtdev/bank-application pull request #2
Opened 2017-01-03 14:09 UTC by dmtdev

По моему я что-то не то делаю в Services.. Особенно в AccountServiceImpl

2017-01-03 20:26 UTC, kongul requested changes
По первой части домашки все ок

2017-01-03 20:26 UTC, kongul commented on src/ua/spalah/bank/services/BankReportServiceImpl.java
> +        List clientList = new ArrayList<>();
List<Clients> clientList = bank.getClients();
for (Client client : clientList) { ... }

тогда потом не нужен instanceof и кастование

2017-01-03 20:26 UTC, kongul commented on src/ua/spalah/bank/services/BankReportServiceImpl.java
> +        List clientList = new ArrayList<>();
То же самое

2017-01-03 20:26 UTC, kongul commented on src/ua/spalah/bank/services/BankReportServiceImpl.java
> +        for (Object client : clientList) {
Тут тоже

2017-01-03 20:26 UTC, kongul commented on src/ua/spalah/bank/services/BankReportServiceImpl.java
> +        List clientList = bank.getClients();
И тут

2017-01-03 20:26 UTC, kongul commented on src/ua/spalah/bank/services/ClientServiceImpl.java
> +        for (Object client : clientList) {
и тут

2017-01-03 20:26 UTC, kongul commented on src/ua/spalah/bank/services/ClientServiceImpl.java
> +        for (Object cl : clientList) {
и тут :)

2017-01-03 20:39 UTC, dmtdev commented on src/ua/spalah/bank/services/BankReportServiceImpl.java
> +        List clientList = new ArrayList<>();
Я так пробовал, иде ругалось.. подсказали:
List clientList<Client> = new ArrayList<>();

2017-01-03 20:40 UTC, dmtdev commented
еще вопрос 
в Client.java 
public void addAccount(Account account){
        if (accountList.size()==0){
            // Так же лучше должно быть? На случай если с перед активацией со счетом нужно что-то еще сделать..
            setActiveAccount(account);
        }
        accountList.add(account);
    }
Не прав?

2017-01-04 10:10 UTC, kongul commented
Да так лучше
public void addAccount(Account account){
  if (accountList.size()==0){
    setActiveAccount(account);
   }
}

2017-01-04 10:10 UTC, kongul approved these changes

2017-01-04 12:43 UTC, closed without merging