Посмотри по возможности.
dmtdev/bank-application pull request #6
Opened 2017-01-13 11:09 UTC by dmtdev

Вопросы:
1.Может добавить getter для commands или сделать commands public, чтобы можно было вызвать одну из другой. Если при старте программы пользователь сразу вызывает GetAccountsComman - вывести сообщение, что нужно выбрать клиента и передать управление FindClientCommand

2. AddClientCommand, сделал с вложенным классом, оправдано или нет? + возможно его лучше было сделать static? Там-же сделал добавление 1го аккаунта, не стал уже убирать, ну и вроде сделал так, что execute() не генерирует исключений, надо ли было?

3. Добавил  ShowMenuCommander, ну это так,

2017-01-18 10:23 UTC, kongul requested changes
Общий посыл в том чтобы хендлить все ексепшены в команде и выводить юзеру соответсвующее сообщение с просьбой ввести данные заново

2017-01-18 10:23 UTC, kongul commented on src/ua/spalah/bank/commands/AddAccountCommand.java
> +    public void execute() throws CurrentClientNotSetException, NotEnoughFundsException {
команда не должна кидать эксепшн все должно быть внутри нее, если клиент не выбран, то посто пишем об этом и выходим в меню

2017-01-18 10:23 UTC, kongul commented on src/ua/spalah/bank/commands/BankCommander.java
> +            try {
эксепшены нужно хендлить в каждой команде и писать юзеру соответствующее сообщение ввести данные заново

2017-01-18 10:23 UTC, kongul commented on src/ua/spalah/bank/commands/Command.java
> +    void execute() throws CurrentClientNotSetException, NotEnoughFundsException, ClientNotFoundException;
без эксепшенов

2017-01-18 10:23 UTC, kongul commented on src/ua/spalah/bank/commands/Command.java
> +    String printCommandInfo();
лучше getCommandInfo()

2017-01-20 12:50 UTC, kongul commented on src/ua/spalah/bank/commands/AddAccountCommand.java
> +            System.out.println(new CurrentClientNotSetException().getMessage());
Зачем создавать ексепшн если его не бросать, тут можно просто текст выводить

2017-01-20 13:32 UTC, dmtdev commented on src/ua/spalah/bank/commands/AddAccountCommand.java
> +            System.out.println(new CurrentClientNotSetException().getMessage());
мне так быстрее было переделать..

2017-01-20 13:38 UTC, merged